stages:
  - trigger

EC2-DA_LM-Template:
  stage: trigger
  trigger:
    include: EC2-DA_LM-Template/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        paths:
          - EC2-DA_LM-Template/*